# Proxmox LXC template
# ---
# Variables for proxmox LXC templates
# Variable details can be found at https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container

# Required variables (Should be changed)
# ---
# LXC configuration
lxc_id: 12345
lxc_name: your-lxc-name
lxc_description: your-lxc-description

lxc_node_name: node-where-vm-is

# Network configuration
network_vlan_id: 20
network_dns_domain: your-domain
network_dns_servers:
  - your-dns-server

network_ipv4: 172.28.20.253/24
network_ipv4_gateway: 172.28.20.1

# OS Configuration
os_template_name: debian-12.6-minimal
os_template_type: debian

# Default variables (default values are usually okay)
# ---
# LXC configuration
# Should be sorted, else will always report as a change.
lxc_tags:
  - opentofu
lxc_resource_pool: ""

lxc_start_on_boot: false
lxc_startup_order: 100
lxc_startup_delay: 0
lxc_shutdown_delay: 0

lxc_started: true
lxc_unprivileged: true
lxc_nesting: true

# CPU configuration
cpu_cores: 1

# Memory configuration
memory_size: 512
memory_swap: 512

# Network configuration
network_bridge: vmbr0
network_enable_firewall: true
network_interface_name: eth0

# Storage configuration (cloud-init disk)
storage_pool: local-lvm
storage_size: 8
