# Ansible development environment
# ---
# Variables for the Ansible development LXC container
# Variable details can be found at https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container

# Required variables (Should be changed)
# ---
# LXC configuration
lxc_id: 20253
lxc_name: ansible-lxc
lxc_description: Ansible development environment - LXC

lxc_node_name: sierra

# Network configuration
network_vlan_id: 20
network_dns_domain: tinynamoo.com
network_dns_servers:
  - 172.28.20.1

network_ipv4: 172.28.20.253/24
network_ipv4_gateway: 172.28.20.1

# OS Configuration
os_template_name: debian-12.10-minimal
os_template_type: debian

# Default variables (default values are usually okay)
# ---
# LXC configuration
# Should be sorted, else will always report as a change.
lxc_tags:
  - ansible
  - opentofu
lxc_resource_pool: ""

lxc_start_on_boot: false
lxc_startup_order: 100
lxc_startup_delay: 0
lxc_shutdown_delay: 0

lxc_protection: false
lxc_started: false
lxc_unprivileged: true
lxc_nesting: true

# CPU configuration
cpu_cores: 4

# Memory configuration
memory_size: 4096
memory_swap: 1024

# Network configuration
network_bridge: vmbr0
network_enable_firewall: true
network_interface_name: eth0

# Storage configuration (cloud-init disk)
storage_pool: local-zfs
storage_size: 8
