# Proxmox datacenter firewall aliases
# ---
# Firewall aliases across the proxmox datacenter.

- name: lan
  cidr: "192.168.171.0/24"
  comment: "[LAN] Entire lan network"

- name: tiny_airport_privilege
  cidr: "172.28.149.0/25"
  comment: "[Tiny - Airport Privilege] Wireguard remote VPN privilege users"
