# Proxmox datacenter firewall aliases
# ---
# Firewall aliases across the proxmox datacenter.

- name: lan
  cidr: "192.168.171.0/24"
  comment: "[LAN] Entire lan network"

- name: rosabelle_router_hotel
  cidr: "172.28.14.1"
  comment: "[Rosabelle] OPNsense Tiny_Hotel interface"

- name: rosabelle_router_hq
  cidr: "172.28.10.1"
  comment: "[Rosabelle] OPNsense Tiny_HQ interface"

- name: rosabelle_router_island
  cidr: "172.28.20.1"
  comment: "[Rosabelle] OPNsense Tiny_Island interface"

- name: tiny_airport_all
  cidr: "172.28.149.0/24"
  comment: "[Tiny - Airport All] Wireguard remote VPN all users"

- name: tiny_airport_guests
  cidr: "172.28.149.128/25"
  comment: "[Tiny - Airport Guests] Wireguard remote VPN guest users"

- name: tiny_airport_privilege
  cidr: "172.28.149.0/25"
  comment: "[Tiny - Airport Privilege] Wireguard remote VPN privilege users"

- name: tiny_hq
  cidr: "172.28.10.0/24"
  comment: "[Tiny - Management] Tiny management network"

- name: tiny_hotel
  cidr: "172.28.14.0/24"
  comment: "[Tiny - DMZ] Tiny DMZ network"

- name: tiny_island
  cidr: "172.28.20.0/24"
  comment: "[Tiny - Internal] Tiny internal network"

- name: sierra_proxmox
  cidr: "172.28.1.10"
  comment: "[Sierra] Proxmox hypervisor"
