# Jellyfin media streaming instance firewall rules
# ---
# Firewall rules for the Jellyfin media streaming instance.

presets:
  - name: basic
  - name: uptime
  - name: node-exporter
  - name: web
    vars:
      source_alias: jellyfin_clients
      source_alias_is_ipset: true
      source_description: Jellyfin clients
      application: Jellyfin

specifics:
  - action: ACCEPT
    type: in
    source: sonarr_clients
    source_ipset: true
    dest: sapphire_sonarr
    dest_ipset: false
    macro: HTTPS
    comment: "[Sonarr - HTTPS] [Allow] Sonarr clients to Sapphire Sonarr TV manager"
    log: nolog

options:
