# Immich photos management instance firewall rules
# ---
# Firewall rules for the Immich photos management instance.

presets:
  - name: basic
  - name: uptime
  - name: node-exporter
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Immich

specifics:
  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    dest: rosabelle_router_hotel
    dest_ipset: false
    macro: Ping
    comment: "[OPNsense - ICMP] [Allow] Petal Immich photos management to Rosabelle OPNsense router"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    dest: rosabelle_router_hotel
    dest_ipset: false
    macro: DNS
    comment: "[OPNsense - DNS] [Allow] Petal Immich photos management to Rosabelle OPNsense router DNS server"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    dest: rosabelle_router_hotel
    dest_ipset: false
    macro: NTP
    comment: "[OPNsense - NTP] [Allow] Petal Immich photos management to Rosabelle OPNsense router NTP server"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    dest: seori_nas
    dest_ipset: false
    dest_port: 88
    protocol: udp
    log: notice
    comment: "[NAS - Kerberos KDC] [Allow] Petal Immich photos management to Seori network attached Kerberos KDC server"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    dest: seori_nas
    dest_ipset: false
    dest_port: 2049
    protocol: tcp
    log: notice
    comment: "[NAS - NFSv4] [Allow] Petal Immich photos management to Seori network attached NFSv4 server"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    macro: HTTP
    comment: "[Public - HTTP] [Allow] Petal Immich photos management to Any"

  - action: ACCEPT
    type: out
    source: petal_immich
    source_ipset: false
    macro: HTTPS
    comment: "[Public - HTTPS] [Allow] Petal Immich photos management to Any"

options:
  output_policy: REJECT
