# Gitea git hosting instance firewall rules
# ---
# Firewall rules for the Gitea git hosting instance.

presets:
  - name: basic
  - name: uptime
  - name: node-exporter
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Gitea

specifics:
  - action: ACCEPT
    type: in
    source: gitea_https_clients
    source_ipset: true
    dest: yena_gitea
    dest_ipset: false
    macro: HTTPS
    comment: "[Gitea - HTTPS] [Allow] Gitea HTTPS clients to Yena git hosting server"
    log: nolog

  - action: ACCEPT
    type: in
    source: gitea_ssh_clients
    source_ipset: true
    dest: yena_gitea
    dest_ipset: false
    macro: SSH
    comment: "[Gitea - SSH] [Allow] Gitea SSH clients to Yena git hosting server"
    log: nolog

options:
