# Wikijs wiki engine instance firewall rules
# ---
# Firewall rules for the Wikijs wiki engine instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Prowlarr

specifics:
  - action: ACCEPT
    type: in
    source: prowlarr_clients
    source_ipset: true
    dest: pearl_prowlarr
    dest_ipset: false
    macro: HTTPS
    comment: "[Prowlarr - HTTPS] [Allow] Prowlarr clients to Pearl Prowlarr indexers manager"
    log: nolog

options:
