# Bazarr subtitles managment instance firewall rules
# ---
# Firewall rules for the Bazarr subtitles managment instance.

presets:
  - name: basic
  - name: node-exporter

specifics:
  - action: ACCEPT
    type: in
    source: smtp_clients
    source_ipset: true
    dest: sunny_proton-bridge-relay
    dest_ipset: false
    macro: SMTP
    comment: "[Postfix - SMTP] [Allow] SMTP clients to Sunny Proton bridge smtp relay"
    log: nolog

options:
