# Mat2-web metadata removal tool instance firewall rules
# ---
# Firewall rules for the Mat2-web metadata removal tool instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Mat2-web

specifics: []

options:
