# Jellyseerr media management instance firewall rules
# ---
# Firewall rules for the Jellyseerr media management instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Jellyseerr

specifics:
  - action: ACCEPT
    type: in
    source: hanni_homarr
    source_ipset: false
    dest: juliette_jellyseerr
    dest_ipset: false
    macro: HTTPS
    comment: "[Homarr - HTTPS] [Allow] Homarr dashboard to Juliette Jellyseerr media manager"
    log: nolog

options:
