# qBittorrent download client instance firewall rules
# ---
# Firewall rules for the qBittorrent download client instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: qBittorrent

specifics:
  - action: ACCEPT
    type: in
    source: qbittorrent_clients
    source_ipset: true
    dest: dahlia_qbittorrent
    dest_ipset: false
    macro: HTTPS
    comment: "[qBittorrent - HTTPS] [Allow] qBittorrent clients to Dahlia qBittorrent download client"
    log: nolog

options:
