# Wallos subscription manager instance firewall rules
# ---
# Firewall rules for the Wallos subscription management instance.

presets:
  - name: basic
  - name: node-exporter
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Uptime kuma

specifics: []

options:
