# Scrutiny SMART monitoring instance firewall rules
# ---
# Firewall rules for the Scrutiny SMART monitoring instance.

presets:
  - name: basic
  - name: uptime
  - name: node-exporter
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Scrutiny

specifics:
  - action: ACCEPT
    type: in
    source: scrutiny_clients
    source_ipset: true
    dest: solar_scrutiny
    dest_ipset: false
    macro: HTTPS
    comment: "[Scrutiny - HTTPS] [Allow] Scrutiny clients to Scrutiny smart monitoring service"
    log: nolog

options:
