# Piped youtube proxy instance firewall rules
# ---
# Firewall rules for the Piped youtube proxy instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: IT-Tools

specifics: []
