# Radarr movies manager instance firewall rules
# ---
# Firewall rules for the Radarr movies management instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Radarr

specifics:
  - action: ACCEPT
    type: in
    source: radarr_clients
    source_ipset: true
    dest: rainbow_radarr
    dest_ipset: false
    macro: HTTPS
    comment: "[Radarr - HTTPS] [Allow] Radarr clients to Rainbow radarr movies manager"
    log: nolog
