# Send file sharing instance firewall rules
# ---
# Firewall rules for the Send file sharing instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Send

specifics: []
