# Sonarr TV managment instance firewall rules
# ---
# Firewall rules for the Sonarr TV managment instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Sonarr

specifics:
  - action: ACCEPT
    type: in
    source: sonarr_clients
    source_ipset: true
    dest: sapphire_sonarr
    dest_ipset: false
    macro: HTTPS
    comment: "[Sonarr - HTTPS] [Allow] Sonarr clients to Sapphire Sonarr TV manager"
    log: nolog

options:
