# Vikunja tasks manager instance firewall rules
# ---
# Firewall rules for the Vikunja tasks management instance.

presets:
  - name: basic
  - name: uptime
  - name: web
    vars:
      source_alias: lan_airport_privilege
      source_alias_is_ipset: true
      source_description: LAN & Tiny_Airport privilege
      application: Your-Spotify

specifics: []
